version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - db_uri=postgresql+psycopg://postgres:postgres@db:5432/postgres
    command: ["uvicorn", "src.api:server", "--host", "0.0.0.0"]

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

